server.port=8080

# Kafka
kafka.bootstrap.servers=${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
kafka.topic=weather_status
kafka.group.id=central-station-group

# BitCask
bitcask.directory=${BITCASK_DIR:./data/bitcask}

# Parquet
parquet.directory=${PARQUET_DIR:./data/parquet}
parquet.batch.size=10000
